import Header from "@/components/header/Header";
import Footer from "@/components/shared/Footer";
import { NextUIProvider } from "@nextui-org/react";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "react-hot-toast";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="min-w-screen min-h-screen flex flex-col bg-zinc-300">
                <SessionProvider>
                    <Toaster position="bottom-center" />
                    <Header />
                    <NextUIProvider>{children}</NextUIProvider>
                    <Footer />
                </SessionProvider>
            </body>
        </html>
    );
}
